// The app's single light source: a soft, edge-less radial glow (assets/light.png,
// generated by scripts/make-light.js) tinted and dimmed per use. These are the
// only intensities it is ever shown at, as image opacity on the canvas.
export const LIGHT_SOURCE = require('../../assets/light.png');

export const light = {
  /** A feeling at rest: barely there, "here is a place to touch". */
  rest: 0.06,
  /** A chosen option at rest (Settings): lit, but not a call to action. */
  selected: 0.09,
  /** Under a finger. */
  press: 0.18,
  /** The chosen feeling as the room dissolves into the words. */
  chosen: 0.3,
  /** Warmth behind words being read (lamp tint). */
  read: 0.09,
  /** A primary action at rest / pressed. */
  action: 0.12,
  actionPressed: 0.24,
  /** The breath, fully exhaled / fully inhaled (moon tint). */
  breathOut: 0.12,
  breathIn: 0.26,
} as const;
